### PR TITLE
Include a field layout to Voucher Codes to store additional information

### PR DESCRIPTION
**Pull request by Anubarak**
Please test everything properly again. I spend a lot of time to validate everything and make sure there can't be errors due to changed user input between creating a line item and populating the Code (in case either the field layout changes or the field path changes) invalid fields cause by "user injections" (for example a user submits custom/random values to the API) should be handled properly as well.

I hope I made enough comments so you are able to understand my thoughts and my code.
Please take a look at my `//TODO`s about things I wasn't entirely sure (it's only about changing wordings and uncommenting a line)

The Migration should work correcly, I tested it with a multisite setup and a single site setup but please check it again, just in case. After setting `Code::hasContent` to true, Craft will try to join the content column that is always empty of course and won't find any Codes anymore, so I had to make sure to create empty content rows for the existing codes for the primary site. 

Localization for Codes is still turned off currently, so they won't be propagated. Maybe you want to change that? I wasn't so sure about how to handle multisite for Codes.

Hope you are fine with it an it doesn't cost you more time^^"

### CODE REVIEW

**Comment by engram-design** [comment]
Thanks for putting this together, I'll review and let you know!

**Comment by Anubarak** [comment]
Is there any progress here? If there is something you don't like I could change it - otherwise I'll have to use my fork in the future and merge your changes into mine

**Comment by Anubarak** [comment]
Okay, seems like I have to maintain my own branch and drop the license

**Comment by engram-design** [comment]
Keep this open @Anubarak I just need some proper time to look into this, as the last release was a bit more urgent. I'd like to merge this stuff

**Comment by engram-design** [comment]
Thanks again for your work here, just have a few adjustments to make, but merged into [2.1.0](https://github.com/verbb/gift-voucher/releases/tag/2.1.0)

**Pull request merged**
